# Generated by Django 5.2.1 on 2025-07-26 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
