# Generated by Django 5.2.1 on 2025-08-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
