# Generated by Django 5.2.1 on 2025-08-16 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useractivity_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name_plural': 'User Activities'},
        ),
        migrations.AlterModelOptions(
            name='userstatus',
            options={'verbose_name_plural': 'UserStatus'},
        ),
    ]
