# Generated by Django 5.2.1 on 2025-08-16 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_options_alter_useractivity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstatus',
            options={'verbose_name_plural': 'User Status'},
        ),
    ]
