# Generated by Django 5.2.1 on 2025-08-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
