# Generated by Django 5.2.1 on 2025-08-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_questionthread_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='body',
        ),
    ]
