# Generated by Django 5.2.1 on 2025-08-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_answer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionthread',
            name='seen_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
