# Generated by Django 5.2.1 on 2025-08-03 03:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_questionthread_seen_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionthread',
            name='seen_number',
        ),
        migrations.AddField(
            model_name='questionthread',
            name='seen_users',
            field=models.ManyToManyField(blank=True, related_name='seen_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
